name: Test and Deploy Microservice

on:
  push:
    branches: [ main, develop ]
    paths: [ 'examples/microservice/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'examples/microservice/**' ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/demo-microservice

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: examples/microservice/package-lock.json
        
    - name: Install dependencies
      working-directory: examples/microservice
      run: npm ci
      
    - name: Run linting
      working-directory: examples/microservice
      run: npm run lint
      
    - name: Run unit tests
      working-directory: examples/microservice
      run: npm test
      
    - name: Run integration tests
      working-directory: examples/microservice
      env:
        DATABASE_URL: postgresql://postgres:test_password@localhost:5432/test_db
        NODE_ENV: test
      run: npm run test:integration
      
    - name: Generate test coverage
      working-directory: examples/microservice
      run: npm run coverage
      
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: examples/microservice/coverage/lcov.info
        flags: microservice

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name != 'pull_request'
    
    outputs:
      image: ${{ steps.image.outputs.image }}
      digest: ${{ steps.build.outputs.digest }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
          
    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: examples/microservice
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Output image
      id: image
      run: |
        echo "image=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.0'
        
    - name: Configure kubectl
      run: |
        mkdir -p $HOME/.kube
        echo "$KUBECONFIG" | base64 -d > $HOME/.kube/config
        chmod 600 $HOME/.kube/config
        
    - name: Deploy microservice
      run: |
        # Update the image in the deployment
        sed -i 's|image: .*|image: ${{ needs.build.outputs.image }}|g' examples/k8s/microservice/deployment.yaml
        
        # Apply the deployment
        kubectl apply -f examples/k8s/microservice/
        
    - name: Wait for deployment to be ready
      run: |
        kubectl wait --for=condition=available --timeout=300s deployment/demo-microservice -n postgres-demo
        
    - name: Verify deployment
      run: |
        echo "=== Deployment Status ==="
        kubectl get deployment -n postgres-demo
        echo ""
        echo "=== Pod Status ==="
        kubectl get pods -n postgres-demo -l app=demo-microservice
        echo ""
        echo "=== Service Status ==="
        kubectl get svc -n postgres-demo
        
    - name: Test microservice endpoints
      run: |
        # Port-forward to test the service
        kubectl port-forward -n postgres-demo svc/demo-microservice 8080:8080 &
        PF_PID=$!
        sleep 10
        
        # Test health endpoint
        curl -f http://localhost:8080/health || exit 1
        
        # Test API endpoints
        curl -f http://localhost:8080/api/users || exit 1
        curl -f http://localhost:8080/api/tasks || exit 1
        
        # Clean up
        kill $PF_PID